Version 4.3.1
contao/newsletter-bundle pull request #4
Opened 2016-12-16 10:59 UTC by leofeyer

2016-12-19 17:40 UTC, ausi approved these changes

2016-12-20 08:37 UTC, aschempp requested changes

2016-12-20 08:37 UTC, aschempp commented on src/Resources/contao/languages/en/tl_newsletter.xlf
> +        <source>In case the sending process is interrupted, you can enter a numeric offset here to continue with a particular recipient. You can check how many mails have been sent in the &lt;em&gt;v
The path name should be set dynamically from `$kernel->getLogsDir()`

2016-12-20 08:44 UTC, Toflar approved these changes
See comment of @aschempp, otherwise 👍

2016-12-20 09:30 UTC, leofeyer commented on src/Resources/contao/languages/en/tl_newsletter.xlf
> +        <source>In case the sending process is interrupted, you can enter a numeric offset here to continue with a particular recipient. You can check how many mails have been sent in the &lt;em&gt;v
Changed in 91a305b4c7d2172b5340b9da6f727997aa9d4295.

2016-12-20 10:43 UTC, aschempp approved these changes

2016-12-20 20:13 UTC, discordier approved these changes

2016-12-21 19:41 UTC, merged